"""SAS-SMOTE (Safe-Area SMOTE) class-imbalance augmentation (TEMPO-DQ Framework).

For every minority class, a k-NN classifier first filters the class down to
its "safe" samples — those a k-NN fit on the whole dataset would still label
correctly. Synthetic samples are then generated by stepping from a safe sample
towards its nearest majority-class neighbour, staying within that "safe area"
so the synthetic point does not cross into majority territory. For large
datasets, the k-NN classifier is fit on a random subsample (plus every
minority sample) to keep the search tractable.

Reference (per minority class ``c``):
    n_gen = max_c' |X^(c')| - |X^(c)|
    X_safe = { x in X^(c) : kNN(X, y).predict(x) == c }
    t(x) = NN_1(x, X^(maj))                       nearest majority neighbour
    r(x) = t(x) - x
    alpha ~ Uniform[0, 1]
    x_syn = x - alpha * r(x),   x ~ Uniform(X_safe)
"""

import numpy as np
from sklearn.neighbors import KNeighborsClassifier, NearestNeighbors

# =============================================================================
# CONFIG
# =============================================================================

# Number of neighbours used both to determine "safe" minority samples and to
# find the nearest majority neighbour used as the interpolation target.
K_NEIGHBORS = 5

# Seed for every random operation (subsampling + sample selection + interpolation).
RANDOM_STATE = 42

# Cap on the number of samples used to fit the k-NN safety classifier; the
# dataset is subsampled (minority samples are always kept) above this size.
MAX_SAMPLES_KNN = 50_000


# =============================================================================
# SAS-SMOTE
# =============================================================================

class SasSmote:
    """Oversample minority classes by interpolating within their safe area.

    Parameters
    ----------
    k_neighbors : int
        Neighbourhood size used for the safety check and the majority-neighbour
        search.
    random_state : int
        Seed controlling subsampling, sample selection and interpolation
        coefficients.
    max_samples_knn : int
        Maximum number of samples used to fit the k-NN safety classifier;
        larger datasets are randomly subsampled (minority samples are always
        kept) to keep the fit tractable.
    """

    def __init__(self, k_neighbors=K_NEIGHBORS, random_state=RANDOM_STATE,
                 max_samples_knn=MAX_SAMPLES_KNN):
        self.k_neighbors = k_neighbors
        self.random_state = random_state
        self.max_samples_knn = max_samples_knn

    def fit_resample(self, X, y):
        """Return ``(X_res, y_res)`` with every minority class grown to the
        majority count. The original samples are preserved; only synthetic
        minority samples are appended.
        """
        rng = np.random.default_rng(self.random_state)
        X = np.asarray(X, dtype=np.float64)
        y = np.asarray(y)

        classes, counts = np.unique(y, return_counts=True)
        majority_count = counts.max()
        majority_class = classes[counts.argmax()]
        X_maj = X[y == majority_class]

        X_res, y_res = [X], [y]

        for cls in classes:
            if cls == majority_class:
                continue

            X_min = X[y == cls]
            n_to_gen = majority_count - len(X_min)
            if n_to_gen <= 0:
                continue

            # Subsample the fitting set when it is too large for a fast k-NN fit.
            n_total = len(X)
            if n_total > self.max_samples_knn:
                sub_idx = rng.choice(n_total, size=self.max_samples_knn, replace=False)
                min_idx = np.where(y == cls)[0]
                sub_idx = np.union1d(sub_idx, min_idx)
                X_sub, y_sub = X[sub_idx], y[sub_idx]
            else:
                X_sub, y_sub = X, y

            # Safe minority samples: those a k-NN fit on the dataset still
            # classifies correctly.
            knn = KNeighborsClassifier(n_neighbors=self.k_neighbors, algorithm="ball_tree")
            knn.fit(X_sub, y_sub)
            X_safe = X_min[knn.predict(X_min) == cls]
            if len(X_safe) == 0:
                X_safe = X_min

            # Nearest majority neighbour per safe sample (vectorised).
            nn_maj = NearestNeighbors(n_neighbors=1, algorithm="ball_tree")
            nn_maj.fit(X_maj)
            _, nn_idx = nn_maj.kneighbors(X_safe)
            nearest_maj = X_maj[nn_idx[:, 0]]
            r_vecs = nearest_maj - X_safe

            # Step from a random safe sample towards its majority neighbour.
            sample_idx = rng.integers(0, len(X_safe), size=n_to_gen)
            alphas = rng.random(n_to_gen)
            X_syn = X_safe[sample_idx] - alphas[:, None] * r_vecs[sample_idx]

            X_res.append(X_syn)
            y_res.append(np.full(n_to_gen, cls))

            print(f'  Class "{cls}": {len(X_min):,} -> {len(X_min) + n_to_gen:,} '
                  f"(+{n_to_gen:,} synthetic, safe={len(X_safe):,})")

        return np.vstack(X_res), np.concatenate(y_res)


# =============================================================================
# EXAMPLE
# =============================================================================

if __name__ == "__main__":
    # Minimal usage example on a synthetic imbalanced dataset.
    rng = np.random.default_rng(RANDOM_STATE)
    X = np.vstack([
        rng.normal(0.0, 1.0, size=(100, 5)),  # majority class
        rng.normal(3.0, 1.0, size=(20, 5)),   # minority class
    ])
    y = np.array(["majority"] * 100 + ["minority"] * 20)

    smote = SasSmote(k_neighbors=K_NEIGHBORS, random_state=RANDOM_STATE)
    X_res, y_res = smote.fit_resample(X, y)

    print(f"Before: {len(y):,} samples -> After: {len(y_res):,} samples")
